name: Deploy Build

on:
  push:
    branches:
      - master
      - dev
      - rk4-hot-seren
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Checkout code
      uses: actions/checkout@v2

    - name: npm install
      run: npm install

    - name: Install deps
      run: npm ci

    - name: Build
      run: npm run build

    - name: Upload build result
      uses: actions/upload-artifact@v1
      with:
        name: public
        path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: public
      - name: Transfer build files to server
        uses: appleboy/scp-action@0.0.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY   }}
          source: "public"
          target: "/home/ubuntu/front/public"
